# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be05604e70b43e45fb9f844ba4dfd6ff14199dd9c505f902573a7115bf17da763380097c45fd01a76d3390e08908fb7cd830a54177bb09bc854df26e72ff80d6

test:
  secret_key_base: aca703eb0f45cd3591391ec2491c74c2773387c2b72cd45cbda78248d8622ee5605cfa521f94c5639ae397b5e887361e138451c37315a443f6677bbd619e6703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
